use ${hiveconf:db_name};

CREATE EXTERNAL TABLE IF NOT EXISTS barcode_record (
       id                      bigint,
       passager_name           string,
       flight                  string,
       flight_date             string,
       ship                    string,
       seat_no                 string,
       boarding_no             string,
       start_city              string,
       end_city                string,
       gate_name               string,
       first_scan_time         string,
       last_scan_time          string,
       scan_number             bigint,
       error_code              string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hiveconf:hdfs_path}/BARCODE_RECORD';

CREATE EXTERNAL TABLE IF NOT EXISTS log_sec_scosprsc (
       SC_FFID					string,
       SC_BRDNO					string,
       OPERATION_DATE			string,
       FLIGHT_NO				string,
       SC_SEAT					string,
       SC_DEPT					string,
       SC_INOUT					string,
       SC_PASSFLAG				string,
       SC_SCTM					string,
       SC_FIELD					string,
       SC_SCCM					string,
       SC_SCLOC					string,
       SC_HANDFLAG				string,
       SC_CTYPE					string,
       SC_CNUMBER				string,
       SC_CVALIDATE				string,
       SC_CDEP					string,
       SC_ADDRESS				string,
       SC_BIRTHDAR				string,
       SC_NATION				string,
       SC_CHNNAME				string,
       SC_NAME					string,
       SC_GENDER				string,
--       SC_PSRPHOTO				binary, -- sqoop does not support to import blob field from oracle
       SC_PSCID					string,
       FLGT_ID					string,
       MB_ID					bigint,
       PROCESS_STATUS			string,
       LAST_UPDATE_DATE	    	string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hiveconf:hdfs_path}/LOG_SEC_SCOSPRSC';

CREATE EXTERNAL TABLE IF NOT EXISTS log_sec_ajxxb (
       sysid                   string,
       ajxxb_id                bigint,
       lk_id                   bigint,
       safe_flag               string,
       safe_no                 string,
       safe_oper               string,
       safe_time               string,
       bag_open                string,
       safe_out                string,
       safe_outno              string,
       safe_outtime            string,
       file_name               string,
       lk_date                 string,
       lk_flight               string,
       flgt_id                 string,
       process_status          string,
       last_update_date        string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hiveconf:hdfs_path}/LOG_SEC_AJXXB';

CREATE EXTERNAL TABLE IF NOT EXISTS log_sec_dcspnck (
       ck_ffid                 string,
       ck_brdno                int,
       operation_date          string,
       flight_no               string,
       ck_loc                  string,
       ck_dept                 string,
       ck_prsta                string,
       ck_dest                 string,
       ck_name                 string,
       ck_chnname              string,
       ck_gender               string,
       ck_ics                  string,
       ck_vip                  string,
       ck_seat                 string,
       ck_class                string,
       ck_inf                  string,
       ck_gates                string,
       ck_ctct                 string,
       ck_cert                 string,
       ck_etfl                 string,
       ck_etno                 string,
       ck_fffr                 string,
       ck_group                string,
       ck_bags                 int,
       ck_bagwgt               int,
       ck_depttm               string,
       ck_sip                  string,
       ck_ckipid               string,
       ck_ckiagt               string,
       ck_ckitm                string,
       ck_ckiofc               string,
       ck_tsflag               string,
       flgt_id                 string,
       mb_id                   bigint,
       process_status          string,
       last_update_date        string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hiveconf:hdfs_path}/LOG_SEC_DCSPNCK';

CREATE EXTERNAL TABLE IF NOT EXISTS log_sec_lkxxb (
       sysid                   string,
       lk_id                   string,
       lk_flight               string,
       lk_date                 string,
       lk_seat                 string,
       lk_strt                 string,
       lk_dest                 string,
       lk_bdno                 string,
       lk_ename                string,
       lk_cname                string,
       lk_card                 string,
       lk_cardid               string,
       lk_nation               string,
       lk_sex                  string,
       lk_tel                  string,
       lk_resr                 string,
       lk_inf                  string,
       lk_infname              string,
       lk_class                string,
       lk_chkn                 string,
       lk_chkt                 string,
       lk_gateno               string,
       lk_vip                  string,
       lk_insur                string,
       lk_outtime              string,
       lk_del                  string,
       ajxxb_id                string,
       safe_time               string,
       flgt_id                 string,
       file_name               string,
       process_status          string,
       last_update_date        string)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hiveconf:hdfs_path}/LOG_SEC_LKXXB';